Modularity
NikolaiKuhar/jd2-64-19 pull request #2
Opened 2019-12-01 14:02 UTC by NikolaiKuhar

2019-12-02 13:09 UTC, aliandr13 commented on project-parent/Comics-web/pom.xml
> +  <artifactId>Comics-web</artifactId>
артифакт принято называть с маленькой буквы

2019-12-02 13:09 UTC, aliandr13 commented on project-parent/Comics-common/pom.xml
> +  <artifactId>Comics-common</artifactId>
артифакт принято называть с маленькой буквы

2019-12-05 08:39 UTC, NikolaiKuhar commented
Исправил название артефактов, но есть проблема,не добавляются в гит игнор два iml файла,не понимаю почему.

2019-12-05 08:40 UTC, aliandr13 requested changes

2019-12-05 08:40 UTC, aliandr13 commented on project-parent/сomics-common/сomics-common.iml
> +<?xml version="1.0" encoding="UTF-8"?>
надо удалить 
 в терминале идеи набираем
`git rm --cached project-parent/сomics-common/сomics-common.iml`
коммит пуш

2019-12-05 08:40 UTC, aliandr13 commented on project-parent/сomics-web/сomics-web.iml
> +<?xml version="1.0" encoding="UTF-8"?>
надо удалить
 в терминале идеи набираем
`git rm --cached project-parent/сomics-web/сomics-web.iml`
коммит пуш

2019-12-05 09:28 UTC, aliandr13 approved these changes

2019-12-05 09:29 UTC, merged